### ISSUE TITLE
Does not work with the chignolin molecule  also

### ISSUE THREAD

**Issue by anandojha** [degiacom/molearn#2]
Hii, I have tried this with the chignolin and the alanine dipeptide molecule and it seems not to work!! Hope someone responds to this

**Comment by degiacom** [comment]
This is unsurprising, molearn has not been designed to handle such small molecules. The kernel size used would be larger (for alanine dipeptide) or closely matching the dimensionality of input data. The largest protein we have currently tested it with alpha-B crystallin, has a sequence more than one order of magnitude longer than chignolin.
